#!/usr/bin/with-contenv bash

if [ ! -d /data/jackett ]; then
  echo "Creating /data/jackett"
  mkdir -p /data/jackett
  chown -R abc:abc /data/jackett
fi

if [ ! -d /share/jackett ]; then
  echo "Creating /share/jackett"
  mkdir -p /share/jackett
  chown -R abc:abc /share/jackett
fi